### ISSUE TITLE
Types packages are being included as dependencies in `mdxts` package

### ISSUE THREAD

**Issue by fuma-nama** [souporserious/mdxts#125]
## The Problem

I added `mdxts` to my Next.js project, and surprisingly it downloaded +172 packages into my `node_modules`, it is quite a scary number. After some debugging, I found types packages, like `@types/react` and `@types/title` are being included as dependencies.

## The Solution

Move these packages to `devDependency`.

Despite the large amount of dependencies, it is absolutely a good library!
It would be nice if unused dependencies can be reduced by separating `mdxts` into multiple packages.

**Comment by souporserious** [comment]
This was partially on purpose since the TypeScript Compiler needs the types to display them correctly in the quick info tooltip. However, I agree it bloats dependencies and doesn't let you choose which type versions to include which should be possible. I'll get rid of these in the next version, appreciate you flagging!

I've also been trying to be weary of how many dependencies have accrued 😅 I might move some more smaller dependencies into the core if possible and eventually will probably break them up into more granular packages throughout the monorepo.
